aidevs_api_key = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
openai_api_key = "xxxxxxxxxxxxxxxx"
central_domain = "domain.xyz"
local_ollama_server = "localhost:11434"
qdrant_api_key = "xxxxxxxxxxxxxxxx"
qdrant_host = "xxxxxxxx-xxxx-xxxx...cloud.qdrant.io"
